python build_index.py ^
  --src ./html ^
  --out ./index ^
  --ngram 3 ^
  --min-df 2 ^
  --max-df 0.95 ^
  --title-weight 10 ^
  --heading-weight 4 ^
  --drop-selectors "nav,footer,header,aside,.sidebar,.breadcrumbs" ^
  --embed-model ./.models/sentence-bert-base-ja-mean-tokens-v2 ^
  --embed-max-chars 800 ^
  --embed-overlap 200 ^
  --embed-batch-size 32
